#!/bin/bash
source 00_vars.sh

SHOPPING_URL=$CF_SHOPPING_URL
SHOPPING_ADMIN_URL=$CF_SHOPPING_ADMIN_URL
REDDIT_URL=$CF_REDDIT_URL
GITLAB_URL=$CF_GITLAB_URL
WIKIPEDIA_URL=$CF_WIKIPEDIA_URL
GITLAB_BASE_URL=$CF_GITLAB_EXTERNAL_URL
SHOPPING_BASE_URL=$CF_SHOPPING_BASE_URL
SHOPPING_ADMIN_BASE_URL=$CF_SHOPPING_ADMIN_BASE_URL